#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 The TWRP Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a-branchprot
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := s5e8835
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := $(PRODUCT_PLATFORM)

# Kernel
BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/mkbootimg.mk

TARGET_KERNEL_ARCH := $(TARGET_ARCH)
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image

# DTB / DTBO (FIX UFDT)
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_PREBUILT_DTBIMAGE := $(DEVICE_PATH)/prebuilt/dtb.img

BOARD_RAMDISK_USE_LZ4 := true

# Kernel cmdline (FIX Samsung UFDT)
BOARD_KERNEL_CMDLINE := \
    bootconfig \
    loop.max_part=7 \
    androidboot.dtbo_idx=0

BOARD_KERNEL_PAGESIZE := 4096

# mkbootimg (CRITICAL FIX - NO DTB HERE)
BOARD_MKBOOTIMG_ARGS := \
    --header_version 2 \
    --os_version 13.0.0 \
    --board SRPWK02A003

# Partitions / layout extras
BOARD_ROOT_EXTRA_FOLDERS := \
    carrier \
    efs \
    optics \
    prism \
    spu \
    system_dlkm

# SELinux
BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy

# AVB
BOARD_AVB_ENABLE := false

# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Partitions
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Dynamic partitions
BOARD_SUPER_PARTITION_SIZE := 11429478400
BOARD_SUPER_PARTITION_GROUPS := group_basic
BOARD_GROUP_BASIC_SIZE := 11425284096
BOARD_GROUP_BASIC_PARTITION_LIST := system odm product vendor vendor_dlkm

BOARD_PARTITION_LIST := $(call to-upper, $(BOARD_GROUP_BASIC_PARTITION_LIST))
$(foreach p, $(BOARD_PARTITION_LIST), $(eval BOARD_$(p)IMAGE_FILE_SYSTEM_TYPE := erofs))
$(foreach p, $(BOARD_PARTITION_LIST), $(eval TARGET_COPY_OUT_$(p) := $(call to-lower, $(p))))

# Encryption
BOARD_USES_METADATA_PARTITION := true

# Fake platform versions (SHRP/TWRP workaround)
PLATFORM_VERSION := 99.87.36
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
PLATFORM_SECURITY_PATCH := 2099-12-31
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
RECOVERY_SDCARD_ON_DATA := true

# TWRP flags
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel/brightness"
TW_MAX_BRIGHTNESS := 510
TW_DEFAULT_BRIGHTNESS := 128
TW_FRAMERATE := 120
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_USE_SERIALNO_PROPERTY_FOR_DEVICE_ID := true
TW_INCLUDE_CRYPTO := true

# SHRP config
SHRP_DEVICE_CODE := a35x
SHRP_PATH := device/samsung/$(SHRP_DEVICE_CODE)
SHRP_MAINTAINER := ChristyGaming18
SHRP_REC_TYPE := Treble
SHRP_DEVICE_TYPE := A/B
SHRP_REC := "/dev/block/bootdevice/by-name/recovery"
SHRP_HAS_RECOVERY_PARTITION := true
SHRP_AB := true
SHRP_EDL_MODE := 1
SHRP_INTERNAL := "/sdcard"
SHRP_EXTERNAL := "/external_sd"
SHRP_OTG := "/usb_otg"
SHRP_FLASH := 1
SHRP_STATUSBAR_RIGHT_PADDING := 58
SHRP_STATUSBAR_LEFT_PADDING := 58
SHRP_NOTCH := true
SHRP_EXPRESS := true
SHRP_EXPRESS_USE_DATA := true
SHRP_DARK := true
SHRP_CUSTOM_FLASHLIGHT := true
SHRP_FONP_1 := "/sys/devices/virtual/camera/flash/rear_flash"
SHRP_FLASH_MAX_BRIGHTNESS := 200
